sudo: required

services:
  - docker

env:
  matrix:
    - DOCKERFILE="10.0"
    - DOCKERFILE="10.1"

before_script:
  - docker version

script:
  - docker build -t ${DOCKERFILE} ./${DOCKERFILE}

after_script:
  - docker images
  - docker ps -a
